Parquet: Handle nested column schema changes when subfield pruning is enabled
Summary:
After schema is changed (new field at depth > 1) and when trying to read files with old schema
we end up with a situation where the type of the newly added field type is derived incorrectly.
When this new field type is merged with type of other subfields within the same column, we get
the following error/.

com.facebook.presto.spi.PrestoException: Error opening Hive split file:/var/folders/kg/8w0vwj4n26db9qwybcwmpml80000gn/T/PrestoTest3674412409435240427/hive_data/tpch/test_subfield_multilevel_pruning/20200619_021654_00016_hyx9i_753399fd-0201-4017-82bf-43c808e41bba (offset=0, length=624): repetition constraint is more restrictive: can not merge type optional group shipdate {
  optional int32 ship_day;
  optional int32 ship_month;
} into repeated group shipdate {
  optional int32 ship_day;
  optional int32 ship_month;
}
at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createCryptoParquetPageSource(ParquetPageSourceFactory.java:418)
at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:157)
at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:300)
at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:123)

Reviewers: vivekb

Reviewed By: vivekb

Subscribers: O4263 subscribe to presto changes

Maniphest Tasks: T6125007, T6135749

Differential Revision: https://code.uberinternal.com/D4548607